export const propiedades_alquiler = [ 
    {
    nombre: "Apartamento en el centro de la ciudad",
    src: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXBhcnRtZW50fGVufDB8MHwwfHx8MA%3D%3D&auto=format&fit=crop&w=700&q=60", //Ingresa aqui la URL de la imagen,
    descripcion: `  Este apartamento de 2 habitaciones está ubicado en el corazón de la ciudad, cerca de todo.`,
    ubicacion: "123 Main Street, Anytown, CA 91234",
    habitaciones: "2 Habitaciones",
    costo: "2.000",
    smoke: false,
    pets: true,
},
{
    nombre: "Apartamento luminoso con vista al mar",
    src: "https://images.unsplash.com/photo-1669071192880-0a94316e6e09?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80", //Ingresa aqui la URL de la imagen,
    descripcion: `Este hermoso apartamento ofrece una vista impresionante al mar`,
    ubicacion: "456 Ocean Avenue, Seaside Town, CA 56789",
    habitaciones: "3 Habitaciones",
    costo: "2.500",
    smoke: true,
    pets: true,
},
{
    nombre: "Condominio moderno en zona residencial",
    src: "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGNvbmRvfGVufDB8MHwwfHx8MA%3D%3D&auto=format&fit=crop&w=1000&q=60", //Ingresa aqui la URL de la imagen,
    descripcion: `Este elegante condominio moderno está ubicado en una tranquila zona residencial`,
    ubicacion: "123 Main Street, Anytown, CA 91234",
    habitaciones: "2 Habitaciones",
    costo: "2.200",
    smoke: false,
    pets: false,
},
{
    nombre: "Apartamento acogedor en la montaña",
    src: "https://cdn.bioguia.com/embed/3d0fb0142790e6b90664042cbafcb1581427139/furgoneta.jpg", //Ingresa aqui la URL de la imagen,
    descripcion: `Este apartamento acogedor está situado en lo alto de una montaña con impresionantes vistas`,
    ubicacion: "789 Mountain Road, Summit Peaks, CA 23456",
    habitaciones: "2 Habitaciones",
    costo: "1.200",
    smoke: true,
    pets: true,
},
];